<h3> Informações Iniciais para Realização da Atividade 1</h3>

<ul>
<li><b>Nome da Base de Dados:</b> Most Selling Video Games Dataset 🎮💸</li>
<li><b>URL:</b> 
<a href="https://www.kaggle.com/datasets/vishardmehta/most-selling-video-games-dataset" target="_blank">
https://www.kaggle.com/datasets/vishardmehta/most-selling-video-games-dataset
</a>
</li>
<li><b>Número de Colunas (Atributos):</b> 10</li>
<li><b>Número de Objetos (Instâncias):</b> 50</li>
<li><b>Número de Rótulos:</b> 2</li>
<li><b>Possui dados faltantes:</b> Sim</li>
<li><b>Possui dados categóricos:</b> Sim</li>
</ul>

<p style="text-align: justify;">
  O código completo apresentado abaixo corresponde à etapa inicial do processo de Mineração de Dados, tendo como foco a leitura e visualização de um dataset, bem como a limpeza e o tratamento de valores nulos e/ou dados inconsistentes ou duvidosos. Essas etapas são fundamentais para garantir maior qualidade e confiabilidade nas análises realizadas nas fases seguintes do processo de mineração de dados.
</p>

<p style="text-align: justify;">
  Essa etapa torna-se necessária devido à grande quantidade de informações coletadas atualmente em diversos setores da sociedade, especialmente por grandes empresas de tecnologia (Big Techs). Entretanto, nem todos os dados coletados são necessariamente úteis ou relevantes para a análise proposta. Assim, o processo de tratamento de dados tem como objetivo filtrar as informações relevantes, além de corrigir inconsistências, tratar valores ausentes ou ignorar dados que não contribuem para a análise pretendida.
</p>

In [1]:

# Importação das bibliotecas Pandas e Numpy para manipulação de DataFrames e manipulação de arrays
import pandas as pd
import numpy as np

In [2]:

# Leitura do arquivo .csv por meio da biblioteca pandas e atribuição à variável original_videogames_df para manipulação dos dados
csv_PATH = 'best_selling_video_games.csv'
original_videogames_df = pd.read_csv(csv_PATH)
processed_videogames_df = pd.read_csv(csv_PATH)

In [3]:

# Visualização inicial das informações do DataFrame original, tabelas, contagem de células com valores não nulos e tipo de dados nas colunas
print("\n")
original_videogames_df.info()

# Visualização do DataFrame completo, possível pelo volume de dados ser baixo
print("\n")
original_videogames_df

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             50 non-null     str
 1   Title            50 non-null     str
 2   Platform(s)      50 non-null     str
 3   Developer(s)     50 non-null     str
 4   Publisher(s)     42 non-null     str
 5   Ref.             10 non-null     str
 6   Releaseyear      50 non-null     str
 7   Sales(millions)  49 non-null     str
 8   Series           45 non-null     str
 9   Table_Number     50 non-null     int64
dtypes: int64(1), str(9)
memory usage: 4.0 KB

,Rank,Title,Platform(s),Developer(s),Publisher(s),Ref.,Releaseyear,Sales(millions),Series,Table_Number
0,1,Minecraft,Multi-platform,Mojang Studios,Mojang Studios,NaN,2011[b],350,Minecraft,1
1,2,Grand Theft Auto V,Multi-platform,Rockstar North,Rockstar Games,NaN,2013,225,Grand Theft Auto,1
2,3,Wii Sports[a],Wii,Nintendo EAD,Nintendo,NaN,2006,82.9,Wii,1
3,4,Red Dead Redemption 2,Multi-platform,Rockstar Games,Rockstar Games,NaN,2018,82,Red Dead,1
4,5,Mario Kart 8/Deluxe,Wii U/Switch,Nintendo EAD/Nintendo EPD(Deluxe),Nintendo,[c],2014,79.05,Mario Kart,1
5,6,PUBG: Battlegrounds,Multi-platform,PUBG Studios,Krafton,NaN,2017,75,PUBG Universe,1
6,7,Terraria,Multi-platform,Re-Logic,Re-Logic/505 Games,NaN,2011,64,NaN,1
7,8,The Witcher 3: Wild Hunt,Multi-platform,CD Projekt Red,CD Projekt,NaN,2015,60,The Witcher,1
8,9,Super Mario Bros.[d],Multi-platform,Nintendo R&D4,Nintendo,NaN,1985,58,Super Mario,1
9,10,Human: Fall Flat,Multi-platform,No Brakes Games,Curve Digital,NaN,2016,55,NaN,1
10,11,Overwatch,Multi-platform,Blizzard Entertainment,Blizzard Entertainment,NaN,2016,50,Overwatch,1
11,The Sims,50,2000,Electronic Arts,NaN,NaN,Maxis,The Sims,Multi-platform,1
12,Stardew Valley,50,2016,Chucklefish/ConcernedApe,NaN,NaN,ConcernedApe,NaN,Multi-platform,1
13,14,Animal Crossing: New Horizons,Nintendo Switch,Nintendo EPD,Nintendo,NaN,2020,49.32,Animal Crossing,1
14,15,Pokémon Red/Blue/Yellow,Multi-platform,Game Freak,Nintendo,[e],1996,47.44,Pokémon,1
15,16,Wii Fit/Plus[f],Wii,Nintendo EAD,Nintendo,[g],2007,43.8,Wii,1
16,17,Call of Duty: Black Ops III,Multi-platform,Treyarch,Activision,NaN,2015,43,Call of Duty,1
17,18,Call of Duty: Modern Warfare,Multi-platform,Infinity Ward,Activision,NaN,2019,41,Call of Duty,1
18,19,Hogwarts Legacy,Multi-platform,Avalanche Software,Warner Bros. Games,NaN,2023,40,Wizarding World,1
19,Payday 2,40,2013,505 Games,NaN,NaN,Overkill Software,Payday,Multi-platform,1
20,Sonic the Hedgehog[h],40,1991,Sega,NaN,NaN,Sonic Team,Sonic the Hedgehog,Multi-platform,1
21,22,Super Smash Bros. Ultimate,Nintendo Switch,Bandai Namco Studios/Sora Ltd.,Nintendo,NaN,2018,37.44,Super Smash Bros.,1
22,23,Mario Kart Wii[i],Wii,Nintendo EAD,Nintendo,NaN,2008,37.38,Mario Kart,1
23,24,The Legend of Zelda: Breath of the Wild,Multi-platform,Nintendo EPD,Nintendo,[j],2017,35.34,The Legend of Zelda,1
24,25,Tetris(Game Boy)[k],Game Boy,Nintendo R&D1,Nintendo,NaN,1989,35,Tetris,1
25,Cyberpunk 2077,35,2020,CD Projekt,NaN,NaN,CD Projekt Red,Cyberpunk,Multi-platform,1
26,27,Wii Sports Resort[l],Wii,Nintendo EAD,Nintendo,NaN,2009,33.14,Wii,1
27,28,New Super Mario Bros.,Nintendo DS,Nintendo EAD,Nintendo,NaN,2006,30.8,Super Mario,1
28,29,New Super Mario Bros. Wii,Wii,Nintendo EAD,Nintendo,NaN,2009,30.32,Super Mario,1
29,30,Super Mario Odyssey,Nintendo Switch,Nintendo EPD,Nintendo,NaN,2017,30.27,Super Mario,1
30,31,Pokémon Gold/Silver/Crystal,Game Boy Color,Game Freak,Nintendo,[m],1999,30.12,Pokémon,1
31,32,Elden Ring,Multi-platform,FromSoftware,Bandai Namco,NaN,2022,30,Elden Ring,1
32,Borderlands 2,30,2012,2K Games,NaN,NaN,Gearbox Software,Borderlands,Multi-platform,1
33,Call of Duty: Black Ops Cold War,30,2020,Activision,NaN,NaN,Treyarch/Raven Software,Call of Duty,Multi-platform,1
34,The Elder Scrolls V: Skyrim,30,2011,Bethesda Softworks,NaN,NaN,Bethesda Game Studios,The Elder Scrolls,Multi-platform,1
35,36,Monster Hunter: World,Multi-platform,Capcom,Capcom,[n],2018,29.1,Monster Hunter,1
36,37,Duck Hunt[o],Famicom / NES,Nintendo R&D1,Nintendo,NaN,1984,28.3,NaN,1
37,38,Pokémon Scarlet/Violet,Nintendo Switch,Game Freak,Nintendo/The Pokémon Company,NaN,2022,28.08,Pokémon,1
38,39,Wii Play[p],Wii,Nintendo EAD,Nintendo,NaN,2006,28.02,Wii,1
39,40,Black Myth: Wukong,Multi-platform,Game Science,Game Science,NaN,2024,28,Black Myth,1
40,41,Grand Theft Auto: San Andreas,Multi-platform,Rockstar North,Rockstar Games,NaN,2004,27.5,Grand Theft Auto,1
41,42,Pokémon Sword/Shield,Nintendo Switch,Game Freak,Nintendo/The Pokémon Company,NaN,2019,27.08,Pokémon,1
42,43,It Takes Two,Multi-platform,Hazelight Studios,Electronic Arts,NaN,2021,27,NaN,1
43,44,The Last of Us/Remastered,PS3/PS4,Naughty Dog,Sony Computer Entertainment,[q],2013,26.6,The Last of Us,1
44,45,Call of Duty: Modern Warfare 3,Multi-platform,Infinity Ward/Sledgehammer,Activision,NaN,2011,26.5,Call of Duty,1
45,46,Call of Duty: Black Ops,Multi-platform,Treyarch,Activision,NaN,2010,26.2,Call of Duty,1
46,47,Marvel's Spider-Man/Remastered,Multi-Platform,Insomniac Games,Sony Interactive Entertainment,[r],2018,26.1,Marvel's Spider-Man,1
47,48,Pokémon Sun/Moon/Ultra Sun/Ultra Moon,Nintendo 3DS,Game Freak,Nintendo/The Pokémon Company,[s],2016,25.59,Pokémon,1
48,49,Garry's Mod,PC,Facepunch Studios,Valve,NaN,2006,25.56,NaN,1
49,50,Pokémon Diamond/Pearl/Platinum,Nintendo DS,Game Freak,Nintendo/The Pokémon Company,[t],2006,25.5,Pokémon,1

<p style="text-align: justify;">
A leitura inicial da base de dados escolhida revela a presença de informações desnecessárias, dados ruidosos e valores ausentes, tornando necessária a utilização de técnicas e ferramentas de tratamento de dados. Conforme afirmam Castro e Ferrari (2016, p. 105): “Assim, as ferramentas para a limpeza de dados atuam no sentido de imputar valores ausentes, suavizar ruídos, identificar valores discrepantes (outliers) e corrigir inconsistências.”
</p>

<p style="text-align: justify;">Observa-se também que, das 10 colunas presentes no conjunto de dados, 9 são tratadas como dados do tipo String. Mesmo contendo valores numéricos, esses dados estão inicialmente representados como texto, sendo necessária sua conversão para tipos numéricos apropriados em etapas posteriores do tratamento de dados. Além disso, as colunas “Ref.” e “Table_Number” não apresentam informações relevantes para a análise proposta e, portanto, podem ser desconsideradas nas etapas posteriores do processo de análise de dados.
</p>

<p style="text-align: justify;">Durante a inspeção inicial do dataset, também foram identificadas linhas problemáticas, contendo dados desordenados ou incompatíveis com a estrutura do restante da base. Além disso, observam-se alguns erros de digitação e a presença de marcações textuais junto a determinados valores, como por exemplo “[a]”, que acompanham nomes ou categorias e não contribuem para a análise.
</p>

<p style="text-align: justify;">Dessa forma, com base na visualização inicial do conjunto de dados, é possível identificar os principais problemas presentes na base e definir possíveis estratégias para o tratamento dessas inconsistências. Contudo, nota-se que o dataset possui uma quantidade relativamente pequena de registros disponíveis. Assim, o descarte de linhas contendo valores nulos tende a ser evitado, de modo a preservar o maior volume possível de dados, exceto no caso das duas colunas anteriormente mencionadas, que não interferem nas demais informações da base.
</p>

In [4]:

# Retirada das colunas sem informações relevantes para a análise de dados com comando .drop
processed_videogames_df.drop(columns = ["Ref.", "Table_Number"], errors = "ignore", inplace = True)

# "Remoção" dos caracteres do tipo: [a], [b], [k]... dos dados no DatFrame com comando .replace para leitura mais limpa
processed_videogames_df.replace(r"\[.*?\]", "", regex=True, inplace=True)

# Tratamento de Valores nulos para a coluna de 'Series', sendo preenchida com o conteúdo de 'Title' para valores nulos
processed_videogames_df["Series"] = processed_videogames_df["Series"].fillna(processed_videogames_df["Title"])

<p style="text-align: justify;">
Ao dispensar as colunas "Ref." e "Table_Number", previamente definidas como irrelevantes para a análise, torna-se possível realizar o tratamento das informações que apresentam erros de escrita, anteriormente mencionados. Esse procedimento consiste na substituição dos caracteres adicionais por um caractere vazio, removendo anotações que não fazem parte do valor original do dado.
</p>

<p style="text-align: justify;">
Um exemplo desse processo pode ser observado no caso em que determinados valores aparecem acompanhados de marcações entre colchetes. Assim, valores como:
</p>

<p style="text-align: center;">
<b>"2011[b]" → "2011"</b>
</p>

<p style="text-align: justify;">
Seguindo esse procedimento e ignorando as linhas problemáticas — entendidas como linhas que apresentam dados fora da ordem ou incompatíveis com a estrutura do restante do dataset, além das duas colunas previamente desconsideradas, observa-se que a única coluna restante contendo valores nulos é a coluna "Series".
</p>

<p style="text-align: justify;">
Com base na análise do contexto da base de dados, que contém informações relacionadas a jogos de plataformas digitais, entende-se que o atributo "Series" representa a franquia ou série à qual um determinado jogo pertence. Como se trata de um dado categórico representado em formato textual, torna-se possível preencher os valores ausentes substituindo-os pelo próprio nome do jogo, informação presente na coluna "Title".
</p>

<p style="text-align: justify;">
Dessa forma, conclui-se que o método de tratamento de dados nulos utilizado neste caso corresponde à imputação manual de valores. Outras abordagens poderiam ser consideradas caso os dados ausentes fossem de natureza numérica. Entretanto, por se tratarem de informações públicas e relativamente conhecidas, como ano de lançamento ou quantidade de vendas, esses valores também poderiam ser obtidos por meio de consulta a fontes externas ou estimados utilizando técnicas estatísticas.
</p>

<p style="text-align: justify;">
Por exemplo, valores numéricos como o número de vendas (em milhões) poderiam ser estimados por meio de médias ou por valores próximos dentro do conjunto de dados, considerando ainda a existência de uma coluna de <i>ranking</i> que estabelece uma ordem coerente entre os jogos, na qual a venda de um título não deve ser inferior à venda do título imediatamente seguinte na classificação.
</p>

In [5]:

# Separação das linhas problemáticas (desordenadas) para facilitação na manipulação dos dados 
problem_indexes = [11, 12, 19, 20, 25, 32, 33, 34]

# Localização das linhas problemáticas pelos índices definidos em problem_indexes e retirada do DataFrame principal com .loc e .drop
# As linhas problemáticas foram armazenadas em um DataFrame secundário com uso do pandas que virou uma matriz com uso do numpy
problem_rows_df = processed_videogames_df.loc[problem_indexes]
processed_videogames_df.drop(index = problem_indexes, inplace = True)
problem_matrix = problem_rows_df.to_numpy()

<p style="text-align: justify;">
Os dados obtidos encontram-se numerados de 0 a 49, totalizando 50 registros. Esse volume relativamente baixo de dados permite a realização de um tratamento mais direto e simplificado das linhas que apresentam informações desordenadas. Durante a inspeção inicial da base, foram identificadas apenas 8 linhas com esse tipo de problema. Além disso, embora essas linhas estivessem desordenadas em relação ao restante do <i>dataset</i>, observou-se que elas ainda mantinham uma ordem consistente entre si.
</p>

<p style="text-align: justify;">
Esse tipo de abordagem manual poderia tornar-se inviável em bases de dados maiores ou mais complexas, especialmente em situações nas quais não exista qualquer tipo de padrão ou ordenação entre os registros classificados como problemáticos.
</p>

<p style="text-align: justify;">
Dessa forma, identificou-se que a ordem ideal das colunas do conjunto de dados é:
</p>

<p style="text-align: center;">
<b>
"Rank", "Title", "Platform(s)", "Developer(s)", "Publisher(s)", "Releaseyear", "Sales(millions)", "Series"
</b>
</p>

<p style="text-align: justify;">
Entretanto, nas linhas consideradas desordenadas, a estrutura observada foi a seguinte:
</p>

<p style="text-align: center;">
<b>
"Title", "Sales(millions)", "Releaseyear", "Publisher(s)", "Developer(s)", "Series", "Platform(s)"
</b>
</p>

<p style="text-align: justify;">
Nota-se, portanto, a ausência da coluna correspondente à informação de "Rank" nessas linhas.
</p>

<p style="text-align: justify;">
Durante a implementação do código, essas linhas foram inicialmente separadas e armazenadas em uma matriz. Posteriormente, essa matriz foi convertida em um DataFrame independente, permitindo que os dados fossem reorganizados de acordo com a ordem correta das colunas. Após esse rearranjo, os registros foram reintegrados ao DataFrame original.
</p>

<p style="text-align: justify;">
A informação referente ao atributo "Rank" pôde ser reconstruída utilizando o identificador (ID) de cada linha. Considerando que o conjunto de dados possui 50 registros ranqueados e que os índices do DataFrame variam de 0 a 49, o valor do ranking pode ser obtido somando-se 1 ao índice de cada linha. Assim, o ranking de cada registro corresponde diretamente ao valor de seu índice acrescido de uma unidade.
</p>

In [6]:

# Criação de um vetor limpo para guardar os valores das linhas problemáticas ordenados
new_matrix = []

# Loop para ordenação de linhas problemáticas, arrumando rank de acordo com index e ordem dos dados
for i in range(len(problem_matrix)):
    row = problem_matrix[i]
    rank = problem_indexes[i] + 1

    new_row = [rank, row[0], row[7], row[5], row[3], row[2], row[1], row[6]]
    new_matrix.append(new_row)

# Transformação em matriz do numpy e impressão para visualização dos dados ordenados corretamente
new_matrix = np.array(new_matrix)
print("\n")
print(new_matrix)
print("\n")

[['12' 'The Sims' 'Multi-platform' 'Maxis' 'Electronic Arts' '2000' '50'
  'The Sims']
 ['13' 'Stardew Valley' 'Multi-platform' 'ConcernedApe'
  'Chucklefish/ConcernedApe' '2016' '50' 'nan']
 ['20' 'Payday 2' 'Multi-platform' 'Overkill Software' '505 Games' '2013'
  '40' 'Payday']
 ['21' 'Sonic the Hedgehog' 'Multi-platform' 'Sonic Team' 'Sega' '1991'
  '40' 'Sonic the Hedgehog']
 ['26' 'Cyberpunk 2077' 'Multi-platform' 'CD Projekt Red' 'CD Projekt'
  '2020' '35' 'Cyberpunk']
 ['33' 'Borderlands 2' 'Multi-platform' 'Gearbox Software' '2K Games'
  '2012' '30' 'Borderlands']
 ['34' 'Call of Duty: Black Ops Cold War' 'Multi-platform'
  'Treyarch/Raven Software' 'Activision' '2020' '30' 'Call of Duty']
 ['35' 'The Elder Scrolls V: Skyrim' 'Multi-platform'
  'Bethesda Game Studios' 'Bethesda Softworks' '2011' '30'
  'The Elder Scrolls']]

In [7]:

# Definição das colunas do DataFrame e transformação da matriz de dados limpos em DataFrame para junção dos dados com o DataFrame principal
original_columns = ["Rank", "Title", "Platform(s)", "Developer(s)", "Publisher(s)", "Releaseyear", "Sales(millions)", "Series"]
problem_rows_rebuild_df = pd.DataFrame(new_matrix, columns = original_columns)

# Junção de ambos os DataFrames para finalização da limpeza dos dados
processed_videogames_df = pd.concat([processed_videogames_df, problem_rows_rebuild_df], ignore_index = True)

In [8]:

# Conversão de colunas numéricas do tipo 'string' para tipo 'int' e 'float' com .astype
processed_videogames_df["Rank"] = processed_videogames_df["Rank"].astype(int)
processed_videogames_df["Releaseyear"] = processed_videogames_df["Releaseyear"].astype(int)
processed_videogames_df["Sales(millions)"] = processed_videogames_df["Sales(millions)"].astype(float)

In [9]:

# Ordenação de todo o Dataframe de acordo com a coluna de rank e reset dos índices para leitura limpa 
processed_videogames_df.sort_values(["Rank"], ascending=True, inplace=True)
processed_videogames_df.reset_index(drop=True, inplace=True)

In [13]:

# Leitura final das informações do Dataframe, tipos das colunas ajustados, valores nulos tratados, colunas irrelevantes descartadas
print("\n")
processed_videogames_df.info()
print("\n")

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rank             50 non-null     int64
 1   Title            50 non-null     str
 2   Platform(s)      50 non-null     str
 3   Developer(s)     50 non-null     str
 4   Publisher(s)     50 non-null     str
 5   Releaseyear      50 non-null     int64
 6   Sales(millions)  50 non-null     float64
 7   Series           50 non-null     str
dtypes: float64(1), int64(2), str(5)
memory usage: 3.3 KB

<p style="text-align: justify;">
A leitura final do DataFrame após a etapa de tratamento de dados revela a ausência de valores nulos, de modo que todas as colunas passam a possuir 50 registros válidos. Além disso, observa-se que as colunas numéricas agora apresentam tipos de dados apropriados, diferentemente da situação inicial, na qual grande parte das informações estava representada apenas como texto.
</p>

<p style="text-align: justify;">
Outro resultado importante do processo de limpeza é que o conjunto de dados passa a conter apenas informações relevantes para a análise proposta. Erros de escrita foram corrigidos, marcações desnecessárias foram removidas e as linhas anteriormente identificadas como desordenadas foram reorganizadas de acordo com a estrutura correta do dataset.
</p>

<p style="text-align: justify;">
Dessa forma, ao final dessa etapa, o conjunto de dados encontra-se estruturado, consistente e adequado para as etapas posteriores do processo de Mineração de Dados, permitindo a realização de análises mais confiáveis e precisas.
</p>

In [11]:

# Visualização dos dados pós tratamento próximos para serem utilizados em etapas futuras
processed_videogames_df

,Rank,Title,Platform(s),Developer(s),Publisher(s),Releaseyear,Sales(millions),Series
0,1,Minecraft,Multi-platform,Mojang Studios,Mojang Studios,2011,350.00,Minecraft
1,2,Grand Theft Auto V,Multi-platform,Rockstar North,Rockstar Games,2013,225.00,Grand Theft Auto
2,3,Wii Sports,Wii,Nintendo EAD,Nintendo,2006,82.90,Wii
3,4,Red Dead Redemption 2,Multi-platform,Rockstar Games,Rockstar Games,2018,82.00,Red Dead
4,5,Mario Kart 8/Deluxe,Wii U/Switch,Nintendo EAD/Nintendo EPD(Deluxe),Nintendo,2014,79.05,Mario Kart
5,6,PUBG: Battlegrounds,Multi-platform,PUBG Studios,Krafton,2017,75.00,PUBG Universe
6,7,Terraria,Multi-platform,Re-Logic,Re-Logic/505 Games,2011,64.00,Terraria
7,8,The Witcher 3: Wild Hunt,Multi-platform,CD Projekt Red,CD Projekt,2015,60.00,The Witcher
8,9,Super Mario Bros.,Multi-platform,Nintendo R&D4,Nintendo,1985,58.00,Super Mario
9,10,Human: Fall Flat,Multi-platform,No Brakes Games,Curve Digital,2016,55.00,Human: Fall Flat
10,11,Overwatch,Multi-platform,Blizzard Entertainment,Blizzard Entertainment,2016,50.00,Overwatch
11,12,The Sims,Multi-platform,Maxis,Electronic Arts,2000,50.00,The Sims
12,13,Stardew Valley,Multi-platform,ConcernedApe,Chucklefish/ConcernedApe,2016,50.00,nan
13,14,Animal Crossing: New Horizons,Nintendo Switch,Nintendo EPD,Nintendo,2020,49.32,Animal Crossing
14,15,Pokémon Red/Blue/Yellow,Multi-platform,Game Freak,Nintendo,1996,47.44,Pokémon
15,16,Wii Fit/Plus,Wii,Nintendo EAD,Nintendo,2007,43.80,Wii
16,17,Call of Duty: Black Ops III,Multi-platform,Treyarch,Activision,2015,43.00,Call of Duty
17,18,Call of Duty: Modern Warfare,Multi-platform,Infinity Ward,Activision,2019,41.00,Call of Duty
18,19,Hogwarts Legacy,Multi-platform,Avalanche Software,Warner Bros. Games,2023,40.00,Wizarding World
19,20,Payday 2,Multi-platform,Overkill Software,505 Games,2013,40.00,Payday
20,21,Sonic the Hedgehog,Multi-platform,Sonic Team,Sega,1991,40.00,Sonic the Hedgehog
21,22,Super Smash Bros. Ultimate,Nintendo Switch,Bandai Namco Studios/Sora Ltd.,Nintendo,2018,37.44,Super Smash Bros.
22,23,Mario Kart Wii,Wii,Nintendo EAD,Nintendo,2008,37.38,Mario Kart
23,24,The Legend of Zelda: Breath of the Wild,Multi-platform,Nintendo EPD,Nintendo,2017,35.34,The Legend of Zelda
24,25,Tetris(Game Boy),Game Boy,Nintendo R&D1,Nintendo,1989,35.00,Tetris
25,26,Cyberpunk 2077,Multi-platform,CD Projekt Red,CD Projekt,2020,35.00,Cyberpunk
26,27,Wii Sports Resort,Wii,Nintendo EAD,Nintendo,2009,33.14,Wii
27,28,New Super Mario Bros.,Nintendo DS,Nintendo EAD,Nintendo,2006,30.80,Super Mario
28,29,New Super Mario Bros. Wii,Wii,Nintendo EAD,Nintendo,2009,30.32,Super Mario
29,30,Super Mario Odyssey,Nintendo Switch,Nintendo EPD,Nintendo,2017,30.27,Super Mario
30,31,Pokémon Gold/Silver/Crystal,Game Boy Color,Game Freak,Nintendo,1999,30.12,Pokémon
31,32,Elden Ring,Multi-platform,FromSoftware,Bandai Namco,2022,30.00,Elden Ring
32,33,Borderlands 2,Multi-platform,Gearbox Software,2K Games,2012,30.00,Borderlands
33,34,Call of Duty: Black Ops Cold War,Multi-platform,Treyarch/Raven Software,Activision,2020,30.00,Call of Duty
34,35,The Elder Scrolls V: Skyrim,Multi-platform,Bethesda Game Studios,Bethesda Softworks,2011,30.00,The Elder Scrolls
35,36,Monster Hunter: World,Multi-platform,Capcom,Capcom,2018,29.10,Monster Hunter
36,37,Duck Hunt,Famicom / NES,Nintendo R&D1,Nintendo,1984,28.30,Duck Hunt
37,38,Pokémon Scarlet/Violet,Nintendo Switch,Game Freak,Nintendo/The Pokémon Company,2022,28.08,Pokémon
38,39,Wii Play,Wii,Nintendo EAD,Nintendo,2006,28.02,Wii
39,40,Black Myth: Wukong,Multi-platform,Game Science,Game Science,2024,28.00,Black Myth
40,41,Grand Theft Auto: San Andreas,Multi-platform,Rockstar North,Rockstar Games,2004,27.50,Grand Theft Auto
41,42,Pokémon Sword/Shield,Nintendo Switch,Game Freak,Nintendo/The Pokémon Company,2019,27.08,Pokémon
42,43,It Takes Two,Multi-platform,Hazelight Studios,Electronic Arts,2021,27.00,It Takes Two
43,44,The Last of Us/Remastered,PS3/PS4,Naughty Dog,Sony Computer Entertainment,2013,26.60,The Last of Us
44,45,Call of Duty: Modern Warfare 3,Multi-platform,Infinity Ward/Sledgehammer,Activision,2011,26.50,Call of Duty
45,46,Call of Duty: Black Ops,Multi-platform,Treyarch,Activision,2010,26.20,Call of Duty
46,47,Marvel's Spider-Man/Remastered,Multi-Platform,Insomniac Games,Sony Interactive Entertainment,2018,26.10,Marvel's Spider-Man
47,48,Pokémon Sun/Moon/Ultra Sun/Ultra Moon,Nintendo 3DS,Game Freak,Nintendo/The Pokémon Company,2016,25.59,Pokémon
48,49,Garry's Mod,PC,Facepunch Studios,Valve,2006,25.56,Garry's Mod
49,50,Pokémon Diamond/Pearl/Platinum,Nintendo DS,Game Freak,Nintendo/The Pokémon Company,2006,25.50,Pokémon

<h3> Referências</h3>

<p style="text-align: justify;">
CASTRO, Leandro Nunes de; FERRARI, Daniel Gomes. <b>Introdução à mineração de dados: conceitos básicos, algoritmos e aplicações.</b> São Paulo: Saraiva, 2016.  
MEHTA, Vishard. <b>Most Selling Video Games Dataset.</b> Kaggle. Disponível em: <a href="https://www.kaggle.com/datasets/vishardmehta/most-selling-video-games-dataset"> https://www.kaggle.com/datasets/vishardmehta/most-selling-video-games-dataset </a>. Acesso em: 7 mar. 2026.
</p>